apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mlops
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mlops
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: songchenxue/api:v1.0
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command:
            - gunicorn
            - -w
            - "2"
            - -b
            - 0.0.0.0:8080
            - "scripts.app:create_app()"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: data-pipeline-secrets
            - configMapRef:
                name: data-pipeline-config