apiVersion: v1
kind: ConfigMap
metadata:
  name: data-pipeline-config
  namespace: mlops
data:
  POSTGRES_DB: "recsys"
  OBJECT_STORE_MOUNT: "/mnt/object"
  BLOCK_STORE_MOUNT: "/mnt/block"

---

apiVersion: v1
kind: Secret
metadata:
  name: data-pipeline-secrets
  namespace: mlops
type: Opaque
stringData:
  # Database
  POSTGRES_USER: "recsys"
  POSTGRES_PASSWORD: "recsys123"
  POSTGRES_DB: "recsys"
  
  # MinIO
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin123"
  
  # API Tokens
  KAGGLE_API_TOKEN: ${KAGGLE_API_TOKEN}
  
  # Airflow Keys & Admin
  AIRFLOW_FERNET_KEY: "2n5sXo9jvQyqLh8r7v1u3w6z0a4bN1c5e8fG2h0iJk="
  AIRFLOW_WEBSERVER_SECRET_KEY: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
  AIRFLOW_ADMIN_USERNAME: "admin"
  AIRFLOW_ADMIN_PASSWORD: "admin123"