apiVersion: v1
kind: Service
metadata:
  name: online-service-external
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: online-service-api
  ports:
  - port: 18080
    targetPort: 18080
    nodePort: 30180 