# -------------------------------
# metadata DB
# -------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata
  namespace: airflow
type: Opaque
stringData:
  connection: "postgresql+psycopg2://recsys:recsys123@postgres.mlops.svc.cluster.local:5432/airflow"

---
# -------------------------------
# fernet key
# -------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
type: Opaque
stringData:
  fernet-key: "2n5sXo9jvQyqLh8r7v1u3w6z0a4bN1c5e8fG2h0iJk="

---
# -------------------------------
# api/webserver secret
# -------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: airflow-api-secret-key
  namespace: airflow
type: Opaque
stringData:
  api-secret-key: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="

---
# -------------------------------
# jwt secret
# -------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: airflow-jwt-secret
  namespace: airflow
type: Opaque
stringData:
  jwt-secret: "randomjwtsecret123456"