apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../11-data-pipeline-config.yaml
  - ../12-online-service-config.yaml
  - ../13-api.yaml
  - ../14-online-service-api.yaml
  - ../15-training-manager.yaml
